version: '3'

services:
  db:
    image: mysql:5.6
    volumes:
      - "./data/db:/var/lib/mysql"
    restart: always
    environment:
      - MYSQL_DATABASE=wordpress
      - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"

  web:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "80:80"
    links:
      - db:mysql
    volumes:
      - "/aldercreek/wordpress:/var/www/html"
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"

